[package]
name = "game-book"
version = "0.1.0"
authors = ["Tom치코 Vojt치코ek <tomas.vojtasek@tipsport.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
